language: node_js
node_js:
  - 13.7.0
cache: yarn
services:
  - docker

stage:
  - test
  - build

jobs:
  - include:
    - stage: test
      before_install:
        - chmod +x project1/script.sh
      script:
        - cd project1
        - ./script.sh
    - script:
        - cd project2
        - ./script.sh
      before_install:
        - chmod +x project2/script.sh
    
    - stage: build
      before_install:
        - chmod +x project1/script.sh
      script:
        - cd project1
        - ./script.sh
    - script:
        - cd project2
        - ./script.sh
      before_install:
        - chmod +x project2/script.sh
