language: node_js
node_js:
  - 13.7.0
cache: yarn
services:
  - docker

stage:
  - test
  - build

jobs:
  - include:
    - stage: test
      install:
        - yarn install
      script:
        - yarn test

    - stage: build
      script:
        - docker build -t tony16019/travis-app .
