language: node_js
node_js:
  - 13.7.0
cache: yarn
services:
  - docker

env:
  - PROJECT=project1
  - PROJECT=project2

stage:
  - test
  - build

jobs:
  - include:
    - stage: test
      before_install:
        - chmod +x $PROJECT/script.sh
      script:
        - cd $TRAVIS_BUILD_DIR/$PROJECT
        - ./script.sh
    - stage: build
      before_install:
        - chmod +x $PROJECT/script.sh
      script:
        - cd $TRAVIS_BUILD_DIR/$PROJECT
        - ./script.sh

# jobs:
#   - include:
#     - stage: test
#       install:
#         - yarn install
#       script:
#         - yarn test

#     - stage: build
#       script:
#         - docker build -t tony16019/travis-app .
