jobs:
  - include:
    - language: node_js
      node_js:
        - 13.7.0
      cache: yarn
      services:
        - docker

      install:
        - yarn install

      - stage: test
        script:
          - yarn test

      - stage: build
        script:
          - docker build -t tony16019/travis-app .